name: platform deployment
on: [push]

env:
  GKE_CLUSTER: ${{ secrets.GKE_PROJECT }}-gke
  GKE_REGION: "europe-north1"
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform init
        run: terraform init

      - name: terraform destroy
        run: terraform destroy -auto-approve=true

      - name: terraform apply
        run: terraform apply -auto-approve=true
        