name: platform deployment
on: [push]

env:
  GKE_CLUSTER: ${{ secrets.GKE_PROJECT }}-gke
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply -auto-approve=true

  deploy-argocd:
    name: deploy argo cd to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create namespace for argocd
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: create namespace argocd
    - name: deploy argocd
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
