name: platform deployment
on: [push]

env:
  GKE_CLUSTER: ${{ secrets.GKE_PROJECT }}-gke
  GKE_ZONE: us-central1
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply -auto-approve=true

  deploy-ingress:
    needs: [create-cluster]
    name: deploy nginx ingress controller in cluster
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: deploy ingress
      uses: deliverybot/helm@v1
      with:
        release: ingress-nginx
        namespace: kube-system
        repo: https://kubernetes.github.io/ingress-nginx
        repo-alias: ingress-nginx
        chart: ingress-nginx/ingress-nginx
      env:
        KUBECONFIG_FILE: ${{ secret.KUBE_CONFIG }}

  deploy-argocd:
    needs: [create-cluster]
    name: deploy argo cd to cluster
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        
    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: create namespace for argocd and deploy argocd
      run: |-
        kubectl create namespace argocd
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
